<?php

use Illuminate\Database\Seeder;
use App\Models\Content;

class ContentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('contents')->delete();

        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 4,
            'version' => 1,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Aktuell liegen uns leider keine Informationen vor. Wir prüfen diese bei der zuständigen Auslandsvertretung. Bitte wenden Sie sich bei Fragen zu den Einreisebestimmungen an die zuständige Botschaft beziehungsweise das Honorarkonsulat.',
            'category' => 1,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 1,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 1,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Unfortunately we do not have any information at the moment. We check this with the responsible foreign representation. If you have any questions regarding entry requirements, please contact the responsible embassy or honorary consulate.',
            'category' => 1,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 2,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 1,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Malheureusement, nous n\'avons pas d\'informations pour le moment. Nous vérifions cela auprès de la représentation étrangère responsable. Si vous avez des questions concernant les conditions d\'entrée, veuillez communiquer avec l\'ambassade ou le consulat honoraire responsable.',
            'category' => 1,
            'lang' => 3,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 3,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 1,
            'idversionbefore' => 1,
            'idversionnext' => 5,
            'version' => 2,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Aktuell liegen uns leider keine Informationen vor. Wir prüfen diese bei der zuständigen Auslandsvertretung. Bitte wenden Sie sich bei Fragen zu den Einreisebestimmungen an die zuständige Botschaft beziehungsweise das Honorarkonsulat!',
            'category' => 1,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 1,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 1,
            'idversionbefore' => 4,
            'idversionnext' => 0,
            'version' => 3,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Aktuell liegen uns leider keine Informationen vor. Bitte wenden Sie sich bei Fragen zu den Einreisebestimmungen an die zuständige Botschaft beziehungsweise das Honorarkonsulat.',
            'category' => 1,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 1,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 2,
            'idversionbefore' => 2,
            'idversionnext' => 0,
            'version' => 3,
            'code1' => 'ke',
            'code2' => 'Keine Einreisebestimmungen',
            'position' => 0,
            'text1' => NULL,
            'content1' => 'Unfortunately we do not have any information at the moment. If you have any questions regarding entry requirements, please contact the responsible embassy or honorary consulate.',
            'category' => 1,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2029-01-01',
            'created_user' => 1,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'NOHREQ',
            'code2' => 'No Health requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>No vaccinations are required.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 2,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'NOHREC',
            'code2' => 'No health recommendations',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>No vaccinations are recommended.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 2,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headhealth',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Gesundheitliche Hinweise</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headhealth',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Health information</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'NOHREC',
            'code2' => 'No health recommendations',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>No vaccinations are recommended.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'nohrec',
            'code2' => 'No Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>No vaccinations are required.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'nohrec',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Es sind keine Impfungen vorgeschrieben.</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'yf',
            'code2' => 'Yellow fever',
            'position' => 1,
            'text1' => 'Yellow fever:',
            'content1' => '<p>When entering from areas infected with yellow fever, a yellow fever vaccination is required (see below).</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'yf',
            'code2' => 'Yellow fever',
            'position' => 1,
            'text1' => 'Gelbfieber:',
            'content1' => '<p>Bei der Einreise aus Gelbfieber-Infektionsgebieten ist eine Gelbfieber-Impfung notwendig (siehe unten).</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'healthreq',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Folgende Impfungen sind bei der Einreise empfohlen:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'healthreq',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>The following vaccinations are recommended upon entry:</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'measles',
            'code2' => 'Measles',
            'position' => 1,
            'text1' => 'Measles:',
            'content1' => '<p>The World Health Organization (WHO) has declared a lack of vaccination against measles to be a threat to global health. Both children and adults should therefore review their vaccination protection and complete it if necessary.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'measles',
            'code2' => 'Measles',
            'position' => 1,
            'text1' => 'Masern:',
            'content1' => '<p>Die Weltgesundheitsorganisation (WHO) hat einen fehlenden Impfschutz gegen Masern zur Bedrohung der globalen Gesundheit erkl&auml;rt. Sowohl Kinder als auch Erwachsene sollten daher ihren Impfschutz &uuml;berpr&uuml;fen und gegebenenfalls vervollst&auml;ndigen.</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'malaria',
            'code2' => 'Malaria',
            'position' => 1,
            'text1' => 'Malaria:',
            'content1' => '<p>Please note that malaria is prevalent in some areas. Prophylactic treatment with malaria medication is recommended.</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'malaria',
            'code2' => 'Malaria',
            'position' => 1,
            'text1' => 'Malaria:',
            'content1' => '<p>Bitte beachten Sie, dass in einigen Gebieten Malaria vorherrscht. Eine prophylaktische Behandlung mit Malariamedikamenten wird empfohlen.</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'headhealth',
            'code2' => 'Headline Health Requirements Record',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Gesundheitliche Hinweise</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'headhealth',
            'code2' => 'Headline Health Requirements Record',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Health information</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'nohrec',
            'code2' => 'No Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Es sind keine Impfungen vorgeschrieben.</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headchild',
            'code2' => 'Headline Children',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Please note that children face these specific health risks:</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headchild',
            'code2' => 'Headline Children',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Bitte beachten Sie, dass f&uuml;r Kinder folgende gesundheitliche Gefahren bestehen:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'yfcountries',
            'code2' => 'Yellow Fever Countries',
            'position' => 1,
            'text1' => 'Countries with current danger of infection from yellow fever:',
            'content1' => '<p>Africa:<br />
Equatorial Guinea, Ethiopia, Angola, Benin, Burkina Faso, Burundi, Democratic Republic of the Congo, Ivory Coast, Gabon, Gambia, Ghana, Guinea, Guinea-Bissau, Cameroon, Kenya, Congo, Liberia, Mali, Mauritania, Niger, Nigeria, Senegal, Sierra Leone, Sudan, South Sudan, Togo, Chad, Uganda, Central African Republic</p>

<p>Central and South America:<br />
Argentina, Bolivia, Brazil, Ecuador, French Guiana, Guyana, Colombia, Panama, Paraguay, Peru, Suriname, Trinidad and Tobago, Venezuela<br />
&nbsp;</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'yfcountries',
            'code2' => 'Yellow Fever Countries',
            'position' => 1,
            'text1' => 'Aktuelle Länder mit Gelbfieberinfektionsgefahr:',
            'content1' => '<p>Afrika:<br />
&Auml;quatorialguinea, &Auml;thiopien, Angola, Benin, Burkina Faso, Burundi, Demokratische Republik Kongo, Elfenbeink&uuml;ste, Gabun, Gambia, Ghana, Guinea, Guinea-Bissau, Kamerun, Kenia, Kongo, Liberia, Mali, Mauretanien, Niger, Nigeria, Senegal, Sierra Leone, Sudan, S&uuml;dsudan, Togo, Tschad, Uganda, Zentralafrikanische Republik</p>

<p>Zentral- und S&uuml;damerika:<br />
Argentinien, Bolivien, Brasilien, Ecuador, Franz&ouml;sisch-Guayana, Guyana, Kolumbien, Panama, Paraguay, Peru, Suriname, Trinidad und Tobago, Venezuela</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'healthrec',
            'code2' => 'Headline Health Recommendations',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Folgende Impfungen sind bei der Einreise empfohlen:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'healthrec',
            'code2' => 'Headline Health Recommendations',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>The following vaccinations are recommended upon entry:</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'healthreq',
            'code2' => 'Headline Health Requirements',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Folgende Impfungen sind bei der Einreise vorgeschrieben:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'healthreq',
            'code2' => 'Headline Health Recommendations',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>The following vaccinations are required upon entry:</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headpreg',
            'code2' => 'headpreg',
            'position' => 1,
            'text1' => 'Headline Pregnant',
            'content1' => '<p>Bitte beachten Sie, dass f&uuml;r Schwangere folgende gesundheitliche Gefahren bestehen:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => 3,
            'updated_ip' => '91.36.156.30',
            'archive' => 1,
            'active' => 0,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'headpreg',
            'code2' => 'Headline Pregnant',
            'position' => 1,
            'text1' => NULL,
            'content1' => '<p>Please note that pregnant women face these specific health risks:</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 2,
            'code1' => 'headpreg',
            'code2' => 'Headline Pregnant',
            'position' => 1,
            'text1' => 'Headline Pregnant',
            'content1' => '<p>Bitte beachten Sie, dass f&uuml;r Schwangere folgende gesundheitliche Gefahren bestehen:</p>',
            'category' => 0,
            'lang' => 1,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 3,
            'created_ip' => '91.36.156.30',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 1,
        ]);
        Content::create([
            'assignto' => 0,
            'idversionbefore' => 0,
            'idversionnext' => 0,
            'version' => 1,
            'code1' => 'xyz',
            'code2' => 'test',
            'position' => 1,
            'text1' => 'Testüberschrift',
            'content1' => '<p>Testtext</p>',
            'category' => 0,
            'lang' => 2,
            'validityfrom' => '2019-01-01',
            'validityto' => '2199-12-31',
            'created_user' => 1,
            'created_ip' => '127.0.0.1',
            'updated_user' => NULL,
            'updated_ip' => NULL,
            'archive' => 0,
            'active' => 0,
        ]);
    }
}
