<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdrHeadTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('adr_head', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('idcrm')->nullable();
            $table->integer('idsubscription')->nullable();
            $table->integer('idsupport')->nullable();
            $table->integer('idparrent')->nullable();
            $table->integer('idchild')->nullable();
            $table->string('matchcode', 100)->nullable()->default('')->index();
            $table->integer('assign_to')->nullable()->default(0)->index();
            $table->integer('adr_head_kind_id')->nullable()->index();
            $table->integer('adr_head_branch_id')->nullable()->index();
            $table->integer('adr_head_role_id')->nullable()->index();
            $table->string('accountnr', 10)->nullable();
            $table->date('birthday')->nullable();
            $table->longText('comment')->nullable();

            $table->integer('created_user')->nullable();
            $table->ipAddress('created_ip', 20)->nullable();
            $table->integer('updated_user')->nullable();
            $table->ipAddress('updated_ip', 20)->nullable();
            $table->boolean('active')->nullable()->default(1)->index();
            $table->boolean('deleted')->nullable()->default(0);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('adr_head');
    }
}
