<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePassCruisevisaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pass_cruisevisa', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('assignto')->default(0)->index();
            $table->integer('idversionbefore')->nullable()->default(0)->index();
            $table->integer('idversionnext')->nullable()->default(0)->index();
            $table->integer('version')->nullable();
            $table->integer('idcountry')->nullable();
            $table->string('sccode', 10)->nullable()->index()->comment('Reederei Code');
            $table->string('scname', 255)->nullable()->comment('Name der Reederei');
            $table->string('scname_en', 255)->nullable();
            $table->string('scname_fr', 255)->nullable();
            $table->string('scname_it', 255)->nullable();
            $table->string('scname_nl', 255)->nullable();
            $table->string('scname_pl', 255)->nullable();
            $table->string('scname_es', 255)->nullable();
            $table->string('scname_pt', 255)->nullable();
            $table->string('scname_be', 255)->nullable();
            $table->string('scname_ru', 255)->nullable();
            $table->string('scrcode', 1000)->nullable()->index()->comment('Route Code');
            $table->string('scrcodeext', 1000)->nullable();
            $table->string('scrname', 255)->nullable()->comment('Name der Route');
            $table->string('scrname_en', 255)->nullable();
            $table->string('scrname_fr', 255)->nullable();
            $table->string('scrname_it', 255)->nullable();
            $table->string('scrname_nl', 255)->nullable();
            $table->string('scrname_pl', 255)->nullable();
            $table->string('scrname_es', 255)->nullable();
            $table->string('scrname_pt', 255)->nullable();
            $table->string('scrname_be', 255)->nullable();
            $table->string('scrname_ru', 255);
            $table->string('countryfromcode', 50)->nullable()->index();
            $table->string('countrytocode', 1000)->nullable()->index();
            $table->string('routes', 1000)->nullable()->index();
            $table->string('countrypassport', 1000)->nullable()->index();
            $table->string('lettercodefrom', 150)->nullable()->index();
            $table->string('lettercodeto', 2000)->nullable()->index();
            $table->integer('passport')->nullable()->default(9);
            $table->integer('temppassport')->nullable()->default(9);
            $table->integer('identitycard')->nullable()->default(9);
            $table->integer('tempidentitycard')->nullable()->default(9);
            $table->integer('passportchild')->nullable()->default(9);
            $table->longText('validity')->nullable();
            $table->integer('latestrequest')->default(0);
            $table->integer('travelwarning')->nullable()->default(0);
            $table->integer('pregnant')->nullable()->default(0);
            $table->integer('child')->nullable()->default(0);
            $table->longText('immunisation')->nullable();
            $table->integer('required')->nullable();
            $table->longText('visa')->nullable();
            $table->longText('visa_en')->nullable();
            $table->longText('visa_fr')->nullable();
            $table->longText('visa_it')->nullable();
            $table->longText('visa_nl')->nullable();
            $table->longText('visa_pl')->nullable();
            $table->longText('visa_es')->nullable();
            $table->longText('visa_pt')->nullable();
            $table->longText('visa_be')->nullable();
            $table->longText('visa_ru')->nullable();
            $table->string('note', 255)->nullable();
            $table->longText('longtext')->nullable();
            $table->longText('longtext_en')->nullable();
            $table->longText('longtext_fr')->nullable();
            $table->longText('longtext_it')->nullable();
            $table->longText('longtext_nl')->nullable();
            $table->longText('longtext_pl')->nullable();
            $table->longText('longtext_es')->nullable();
            $table->longText('longtext_pt')->nullable();
            $table->longText('longtext_be')->nullable();
            $table->longText('longtext_ru')->nullable();
            $table->string('linkresource', 255)->nullable();
            $table->longText('textresource')->nullable();
            $table->integer('resourcechanged')->nullable()->default(0);
            $table->integer('status')->nullable()->default(0)->index();
            $table->integer('importantchange')->nullable()->default(0)->index();
            $table->dateTime('controlled_at')->nullable();
            $table->integer('controlled_user')->nullable();
            $table->string('controlled_ip', 11)->nullable();
            $table->integer('created_user')->nullable();
            $table->string('created_ip', 20)->nullable();
            $table->integer('updated_user')->nullable();
            $table->string('updated_ip', 20)->nullable();
            $table->boolean('archive')->nullable()->default(0);
            $table->boolean('active')->nullable()->default(0)->index();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pass_cruisevisa');
    }
}
