<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 150)->nullable();
            $table->string('name_local', 150)->nullable();
            $table->string('name_en', 150)->nullable();
            $table->string('name_fr', 150)->nullable();
            $table->string('name_it', 150)->nullable();
            $table->string('name_nl', 150)->nullable();
            $table->string('name_pl', 150)->nullable();
            $table->string('name_es', 150)->nullable();
            $table->string('name_pt', 150)->nullable();
            $table->string('name_be', 150)->nullable();
            $table->string('name_ru', 150)->nullable();
            $table->string('code', 2)->nullable();
            $table->string('continent', 50)->nullable();
            $table->string('capital', 50)->nullable();
            $table->string('population', 20)->nullable();
            $table->string('area', 20)->nullable();
            $table->string('coastline', 10)->nullable();
            $table->string('governmentform', 200)->nullable();
            $table->string('currency', 10)->nullable();
            $table->string('currencycode', 10)->nullable();
            $table->string('dialingprefix', 10)->nullable();
            $table->string('birthrate', 10)->nullable();
            $table->string('deathrate', 10)->nullable();
            $table->string('lifeexpectancy', 10)->nullable();
            $table->integer('transitvisa')->nullable();
            $table->longText('transitvisatext')->nullable();
            $table->string('url1', 255)->nullable();
            $table->integer('prio')->nullable()->default(99);
            $table->dateTime('created_at')->nullable();
            $table->integer('created_user')->nullable();
            $table->string('created_ip', 20)->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->integer('updated_user')->nullable();
            $table->string('updated_ip', 20)->nullable();
            $table->tinyInteger('active')->nullable()->default(0);

            $table->index('code', 'countrycode');
            $table->index('prio', 'prio');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
