<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserswebTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('usersweb', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('assignto')->nullable()->default(0);
            $table->integer('idpaymentuser')->nullable()->default(0);
            $table->integer('idcontact')->nullable();
            $table->string('idsec', 50)->nullable();
            $table->string('username', 50)->nullable()->index();
            $table->decimal('level', 2, 0);
            $table->string('role', 20)->default('Member');
            $table->string('password', 50)->nullable();
            $table->string('activationpassword', 50)->nullable();
            $table->string('securequestion', 255)->nullable();
            $table->string('secureanswer', 255)->nullable();
            $table->string('email', 50)->nullable();
            $table->string('realname', 100)->nullable();
            $table->string('forename', 50)->nullable();
            $table->string('surname', 50)->nullable();
            $table->string('address1', 100)->nullable();
            $table->string('zip', 10)->nullable();
            $table->string('city', 50)->nullable();
            $table->string('phone', 50)->nullable();
            $table->string('birthday', 50)->nullable();
            $table->string('note', 255)->nullable();
            $table->string('agency', 20)->nullable()->index();
            $table->string('providers', 200);
            $table->integer('accounttype')->nullable()->default(1)->index()->comment('1=Testaccount VA, 2=Testaccount RB, 3=Veranstalter, 4=Reisebüro, 5=Reisebarater');
            $table->decimal('feeinstall', 15, 2)->nullable();
            $table->decimal('feemonth', 15, 2)->nullable();
            $table->integer('feeinterval')->nullable()->comment('1=monatlich, 2=jährlich');
            $table->integer('accessmaxyear')->nullable()->comment('maximale jährige Zugriffszahlen');
            $table->integer('access2018')->nullable();
            $table->integer('access2019')->nullable();
            $table->integer('access2020')->nullable();
            $table->integer('access2021')->nullable();
            $table->integer('access2022')->nullable();
            $table->date('testvalidity')->nullable()->index();
            $table->integer('testrenewals')->nullable()->default(0);
            $table->date('livefrom')->nullable();
            $table->date('endofuse')->nullable();
            $table->integer('canceltype')->nullable()->default(0);
            $table->date('canceldate')->nullable();
            $table->integer('linkmaxopen')->nullable()->default(1)->index();
            $table->integer('linkmaxtodeparture')->nullable()->default(1)->index();
            $table->integer('linkmaxfromcreate')->nullable()->default(1)->index();
            $table->integer('clienttype')->nullable()->default(1)->index();
            $table->string('cooperation', 200)->nullable();
            $table->integer('techaccess')->nullable()->default(0)->index();
            $table->string('visaplaces', 20)->default('DE');
            $table->integer('showvisaservice')->nullable();
            $table->string('showvisaservicelink', 250)->nullable();
            $table->string('showvisaservicetext', 1000)->nullable();
            $table->string('info1', 30)->nullable();
            $table->string('info2', 30)->nullable();
            $table->string('info3', 30)->nullable();
            $table->string('info4', 30)->nullable();
            $table->string('info5', 30)->nullable();
            $table->string('info6', 30)->nullable();
            $table->string('remember_token', 255)->nullable();
            $table->string('favdestination', 200)->nullable();
            $table->string('favnationality', 200)->nullable();
            $table->string('favlanguage', 2)->nullable();
            $table->string('sitelanguage', 2)->nullable();
            $table->string('logo', 255)->nullable();
            $table->integer('officeNum')->nullable();
            $table->string('street', 255)->nullable();
            $table->string('land', 10)->nullable();
            $table->string('handy', 30)->nullable();
            $table->string('fax', 30)->nullable();
            $table->string('website', 100)->nullable();
            $table->string('nameAccount', 100)->nullable();
            $table->string('bank', 100)->nullable();
            $table->string('theywere', 50)->nullable();
            $table->string('bic', 50)->nullable();
            $table->string('ust', 50)->nullable();
            $table->string('comment', 255)->nullable();
            $table->string('zohoAccountID', 100)->nullable();
            $table->string('providers1', 200);

            $table->boolean('active')->nullable()->default(0)->index();

            $table->integer('created_user')->nullable();
            $table->string('created_ip', 20)->nullable();
            $table->integer('updated_user')->nullable();
            $table->string('updated_ip', 20)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('usersweb');
    }
}
