<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTransitvisaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('transitvisa', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedInteger('assignto')->nullable()->default(0)->index();
            $table->unsignedInteger('idversionbefore')->nullable()->default(0);
            $table->unsignedInteger('idversionnext')->nullable()->default(0);
            $table->unsignedInteger('version')->nullable()->index();

            $table->string('countrytocode', 2)->nullable()->index();
            $table->unsignedInteger('country_id')->nullable()->index();

            $table->boolean('no_info_available')->nullable()->default(0)->index();
            $table->boolean('required')->nullable()->default(0)->index();
            $table->boolean('exception')->nullable()->default(0)->index();

            $table->boolean('active')->nullable()->default(0)->index();
            $table->boolean('importantchange')->nullable()->default(0)->index();
            $table->boolean('checkedandok')->nullable()->default(0)->index();
            $table->boolean('checkedandnotok')->nullable()->default(0)->index();

            $table->string('linkresource', 1000)->nullable();
            $table->string('textresource', 1000)->nullable();

            $table->dateTime('controlled_at')->nullable();
            $table->unsignedInteger('controlled_user')->nullable()->index();
            $table->string('controlled_ip', 45)->nullable();
            $table->unsignedInteger('created_user')->nullable()->index();
            $table->string('created_ip', 45)->nullable();
            $table->unsignedInteger('updated_user')->nullable()->index();
            $table->string('updated_ip', 45)->nullable();
            $table->boolean('archive')->nullable()->default(0);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('transitvisa');
    }
}
