<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateInfosystems2Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('infosystems2', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->char('uuid', 36)->nullable();
            $table->boolean('info1')->nullable()->default(0);
            $table->boolean('info2')->nullable()->default(0);
            $table->boolean('info3')->nullable()->default(0);
            $table->boolean('info4')->nullable()->default(0);
            $table->boolean('entry')->nullable()->default(0);
            $table->boolean('visa')->nullable()->default(0);
            $table->boolean('transitvisa')->nullable()->default(0);
            $table->boolean('health')->nullable()->default(0);
            $table->boolean('cruise')->nullable()->default(0);
            $table->boolean('corona')->nullable()->default(0);
            $table->unsignedInteger('position')->nullable()->default(0);
            $table->unsignedInteger('appearance')->nullable()->default(0);
            $table->string('country', 2)->nullable();
            $table->string('nat', 2)->nullable();
            $table->string('lang', 2)->nullable()->default('1');
            $table->unsignedInteger('tagtype')->nullable();
            $table->string('tagtext', 40)->nullable();
            $table->date('tagdate')->nullable();
            $table->string('header', 100)->nullable();
            $table->string('content', 1000)->nullable();
            $table->dateTime('controlled_at')->nullable();
            $table->unsignedInteger('controlled_user')->nullable();
            $table->string('controlled_ip', 45)->nullable();
            $table->unsignedInteger('created_user')->nullable();
            $table->string('created_ip', 45)->nullable();
            $table->unsignedInteger('updated_user')->nullable();
            $table->string('updated_ip', 45)->nullable();
            $table->boolean('archive')->nullable()->default(0);
            $table->boolean('active')->nullable()->default(0);
            $table->nullableTimestamps();

            $table->unique('uuid', 'infosystems_uuid_unique');
            $table->index('info1', 'infosystems_info1_index');
            $table->index('info2', 'infosystems_info2_index');
            $table->index('info3', 'infosystems_info3_index');
            $table->index('info4', 'infosystems_info4_index');
            $table->index('entry', 'infosystems_entry_index');
            $table->index('visa', 'infosystems_visa_index');
            $table->index('transitvisa', 'infosystems_transitvisa_index');
            $table->index('health', 'infosystems_health_index');
            $table->index('cruise', 'infosystems_cruise_index');
            $table->index('corona', 'infosystems_corona_index');
            $table->index('country', 'infosystems_country_index');
            $table->index('nat', 'infosystems_nat_index');            
            $table->index('position', 'infosystems_position_index');
            $table->index('lang', 'infosystems_lang_index');
            $table->index('tagtype', 'infosystems_tagtype_index');
            $table->index('controlled_user', 'infosystems_controlled_user_index');
            $table->index('created_user', 'infosystems_created_user_index');
            $table->index('updated_user', 'infosystems_updated_user_index');
            $table->index('active', 'infosystems_active_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('infosystems2');
    }
}
