<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateQuicklinksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('quicklinks', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('shorturl', 255)->nullable();
            $table->string('url', 400)->nullable();
            $table->string('email', 150)->nullable();
            $table->tinyInteger('maxopen')->nullable();
            $table->tinyInteger('opened')->nullable();
            $table->timestamp('valid_to')->nullable();
            $table->integer('userid')->nullable()->default(0);
            $table->unsignedInteger('techid')->nullable()->default(0);
            $table->unsignedInteger('web')->nullable()->default(0);
            $table->string('requestid', 50)->nullable()->default('0');
            $table->string('dest', 2)->nullable()->default('0');
            $table->string('nat', 2)->nullable()->default('0');
            $table->string('lang', 2)->nullable()->default('0');
            $table->string('destnat', 5)->nullable()->default('');
            $table->string('destnatlang', 10)->nullable()->default('');
            $table->string('bookingnr', 20)->nullable()->default('0');
            $table->string('traveldate', 10)->nullable()->default('0');
            $table->tinyInteger('checkimportant')->nullable()->default(0);
            $table->timestamp('created_at')->nullable();

            $table->index('shorturl', 'requests_shorturl_index');
            $table->index('userid', 'requests_userid_index');
            $table->index('requestid', 'requests_requestid_index');
            $table->index('dest', 'requests_dest_index');
            $table->index('nat', 'requests_nat_index');
            $table->index('lang', 'requests_lang_index');
            $table->index('bookingnr', 'requests_bookingnr_index');
            $table->index('traveldate', 'requests_traveldate_index');
            $table->index('checkimportant', 'requests_checkimportant_index');
            $table->index('destnat', 'requests_destnat');
            $table->index('destnatlang', 'requests_destnatlang');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('quicklinks');
    }
}
